src/chris/NewsBundle/Entity/Image.php
<?php

namespace chris\NewsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 */
class Image
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $alt;

    private $file;
    
    private $tempFilename;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
    
    public function getFile()
    {
    	return $this->file;
    }
    
    public function setTempFilename($tempFilename)
    {
    	$this->tempFilename = $tempFilename;
    
    	return $this;
    }
    
    public function getTempFilename()
    {
    	return $this->tempFilename;
    }
    
	// On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
	  public function setFile(UploadedFile $file)
	  {
	    $this->file = $file;
	
	    // On vérifie si on avait déjà un fichier pour cette entité
	    if (null !== $this->url) {
	      // On sauvegarde l'extension du fichier pour le supprimer plus tard
	      $this->tempFilename = $this->url;
	
	      // On réinitialise les valeurs des attributs url et alt
	      $this->url = null;
	      $this->alt = null;
	    }
	  }

	
	  public function preUpload()
	  {
	    // Si jamais il n'y a pas de fichier (champ facultatif)
	    if (null === $this->file) {
	      return;
	    }
	
	    // Le nom du fichier est son id, on doit juste stocker également son extension
	    // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
	    $this->url = $this->file->guessExtension();
	
	    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
	    $this->alt = $this->file->getClientOriginalName();
	  }
	
	  
	  public function upload()
	  {
	    // Si jamais il n'y a pas de fichier (champ facultatif)
	    if (null === $this->file) {
	      return;
	    }
	
	    // Si on avait un ancien fichier, on le supprime
	    if (null !== $this->tempFilename) {
	      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
	      if (file_exists($oldFile)) {
	        unlink($oldFile);
	      }
	    }
	
	    // On déplace le fichier envoyé dans le répertoire de notre choix
	    $this->file->move(
	      $this->getUploadRootDir(), // Le répertoire de destination
	      $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
	    );
	  }
	
	  
	  public function preRemoveUpload()
	  {
	    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
	    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
	  }
	
	  
	  public function removeUpload()
	  {
	    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
	    if (file_exists($this->tempFilename)) {
	      // On supprime le fichier
	      unlink($this->tempFilename);
	    }
	  }
	
	  public function getUploadDir()
	  {
	    // On retourne le chemin relatif vers l'image pour un navigateur
	    return 'uploads/img';
	  }
	
	  protected function getUploadRootDir()
	  {
	    // On retourne le chemin relatif vers l'image pour notre code PHP
	    return __DIR__.'/../../../../web/'.$this->getUploadDir();
	  }
	  public function getWebPath()
	  {
	  	return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
	  }
}

src/chris/NewsBundle/Controller/NewsController.php
<?php
namespace chris\NewsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use chris\NewsBundle\Entity\Article;
use chris\NewsBundle\Form\ArticleType;
use chris\NewsBundle\Form\ArticleEditType;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpFoundation\Request;


class NewsController extends Controller
{
	public function accueilAction(Request $request, $page)
	{

		if(
			$this->get('security.context')->isGranted('IS_AUTHENTICATED_FULLY') ||
			$this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')			
		) {
			# L'utilisateur est authentifié
			$_SESSION['useridCometChat']=$this->get('security.context')->getToken()->getUser()->getId();
		} else {
			echo "<h2>Anonyme</h2>";
		}
			
		if( $page < 1 )
		{
			throw $this->createNotFoundException('Page inexistante (page = '.$page.')');
		}
		$nombreParPage=3;
		$articles = $this->getDoctrine()
                     ->getManager()
                     ->getRepository('chrisNewsBundle:Article')
                     ->getArticles($nombreParPage, $page);
		return $this->render('chrisNewsBundle:News:accueil.html.twig',array('articles' => $articles,
																			'page'=> $page,
      																		'nombrePage' => ceil(count($articles)/$nombreParPage)
																			));
	}
	public function voirAction($slug)
	{
	  $em=$this->getDoctrine()->getManager();
	  $article=$em->getRepository('chrisNewsBundle:Article')
                                  ->findOneBy(array('slug'=>$slug));

	  $liste_articleCompetence = $em->getRepository('chrisNewsBundle:ArticleCompetence')
                                  ->findByArticle($article->getId());
	  
	  $allNews = $this->getDoctrine()->getManager()->getRepository('chrisNewsBundle:Article')->getAllArticles();
	  $nextNews = "";
	  $prevNews = "";
	  $i=0;
	  foreach ($allNews as $allN) {
	  	if ($slug === $allN["slug"]){
	  		if ($i !== 0) {
	  			$prevNews = $allNews[$i-1]["slug"];
	  		}
	  		if ($i !== count($allNews)-1) {
	  			$nextNews = $allNews[$i+1]["slug"];
	  		}
	  	}
	  	$i++;
	  
	  }
	  
	  return $this->render('chrisNewsBundle:News:voir.html.twig',array ('nextSlug' => $nextNews,'prevSlug' => $prevNews,'article' => $article,'liste_articleCompetence' => $liste_articleCompetence));
	}
	public function ajouterAction()
	{
		if (!$this->get('security.context')->isGranted('ROLE_AUTEUR')) {
			// Sinon on déclenche une exception « Accès interdit »
			throw new AccessDeniedHttpException('Accès limité aux auteurs');
		}
		// On crée un objet Article
		$article = new Article();
	
		// On crée le FormBuilder grâce à la méthode du contrôleur
		$form = $this->createForm(new ArticleType, $article);
		
	    // Reste de la méthode qu'on avait déjà écrit
	    if ($this->getRequest()->getMethod() == 'POST') {
	    	$form->bind($this->getRequest());
	    	
	    	// On vérifie que les valeurs entrées sont correctes
	    	// (Nous verrons la validation des objets en détail dans le prochain chapitre)
	    	if ($form->isValid()) {
	    		$article->setAuteur($this->get('security.context')->getToken()->getUser());
	    		
	    		// On l'enregistre notre objet $article dans la base de données
	    		$em = $this->getDoctrine()->getManager();
	    		$em->persist($article);
	    		$em->flush();
		      $this->get('session')->getFlashBag()->add('info', 'Article bien enregistré');
		      return $this->redirect( $this->generateUrl('chrisNewsVoir', array('slug' => $article->getSlug() )) );
	    	}
	    }
	    
		return $this->render('chrisNewsBundle:News:ajouter.html.twig',array(
					'form' => $form->createView(),
			));
	}
	public function modifierAction(Article $article)
	{
		if (!$this->get('security.context')->isGranted('ROLE_AUTEUR')) {
			// Sinon on déclenche une exception « Accès interdit »
			throw new AccessDeniedHttpException('Accès limité aux auteurs');
		}
		// On crée le FormBuilder grâce à la méthode du contrôleur
		$article->setDateEdition(new \Datetime());
		$form = $this->createForm(new ArticleEditType(), $article);
		if ($this->getRequest()->getMethod() == 'POST') {
			$form->bind($this->getRequest());
		
			// On vérifie que les valeurs entrées sont correctes
			// (Nous verrons la validation des objets en détail dans le prochain chapitre)
			if ($form->isValid()) {
				// On l'enregistre notre objet $article dans la base de données
				$em = $this->getDoctrine()->getManager();
				$em->persist($article);
				$em->flush();
				$this->get('session')->getFlashBag()->add('info', 'Article bien enregistré');
				return $this->redirect( $this->generateUrl('chrisNewsVoir', array('slug' => $article->getSlug() )) );
			}
		}
		return $this->render('chrisNewsBundle:News:modifier.html.twig',array('article' => $article,'form' => $form->createView()));
	}
	
	public function supprimerAction(Article $article)
	{
		if (!$this->get('security.context')->isGranted('ROLE_AUTEUR')) {
			// Sinon on déclenche une exception « Accès interdit »
			throw new AccessDeniedHttpException('Accès limité aux auteurs');
		}
	   // On crée un formulaire vide, qui ne contiendra que le champ CSRF
	    // Cela permet de protéger la suppression d'article contre cette faille
	    $form = $this->createFormBuilder()->getForm();
	
	    $request = $this->getRequest();
	    if ($request->getMethod() == 'POST') {
	      $form->bind($request);
	
	      if ($form->isValid()) {
	        // On supprime l'article
	        $em = $this->getDoctrine()->getManager();
	        $em->remove($article);
	        $em->flush();
	
	        // On définit un message flash
	        $this->get('session')->getFlashBag()->add('info', 'Article bien supprimé');
	
	        // Puis on redirige vers l'accueil
	        return $this->redirect($this->generateUrl('chrisNewsAccueil'));
	      }
	    }
	
	    // Si la requête est en GET, on affiche une page de confirmation avant de supprimer
	    return $this->render('chrisNewsBundle:News:supprimer.html.twig', array(
	      'article' => $article,
	      'form'    => $form->createView()
	    ));
	}
	public function menuAction($nombre)
	{
		// On fixe en dur une liste ici, bien entendu par la suite on la récupérera depuis la BDD !
		 $liste = $this->getDoctrine()
                  ->getManager()
                  ->getRepository('chrisNewsBundle:Article')
                  ->findBy(
                    array(),          // Pas de critère
                    array('date' => 'desc'), // On trie par date décroissante
                    $nombre,         // On sélectionne $nombre articles
                    0                // À partir du premier
                  );
	
		return $this->render('chrisNewsBundle:News:menu.html.twig', array(
				'liste_articles' => $liste // C'est ici tout l'intérêt : le contrôleur passe les variables nécessaires au template !
		));
	}
}

src/chris/NewsBundle/Resources/views/News/accueil.html.twig
{% extends "chrisNewsBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }} - Accueil
{% endblock %}

{% block newsBody %}

  <h2>Liste des news</h2>

  <ul>
  {% for article in articles %}
    {# On inclut la vue à chaque itération dans la boucle #}
    {% include "chrisNewsBundle:News:article.html.twig" with {'accueil': true} %}
    <hr />
  {% else %}
    <p>Pas (encore !) d'articles</p>
  {% endfor %}
</ul>
 <ul>
  <div class="btn-group">
      {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
      {% for p in range(1, nombrePage) %}
        <a href="{{ path('chrisNewsAccueil', {'page': p}) }}"><div {% if p != page %}class="btn btn-default" {% else %} class="btn btn-primary"{% endif %}>
          {{ p }}
        </div></a>
      {% endfor %}
  </div>
 </ul>
{% endblock %}

src/chris/NewsBundle/Resources/views/News/ajouter.html.twig
{% extends "chrisNewsBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }} - Ajouter un article
{% endblock %}

{% block newsBody %}

  <h2>Ajouter une news</h2>

  {% include "chrisNewsBundle:News:formulaire.html.twig" %}

  <p>
    <a href="{{ path('chrisNewsAccueil') }}" class="btn btn-default btn-success">
      Retour à l'accueil
    </a>
  </p>

{% endblock %}

src/chris/NewsBundle/Resources/views/News/article.html.twig
{% set accueil = accueil|default(false) %}

<h2>
  {# Si on est sur la page d'accueil, on fait un lien vers l'article, sinon non #}
  {% if accueil %}
    <a href="{{ path('chrisNewsVoir', {'slug': article.slug} ) }}">{{ article.titre }}</a>
  {% else %}
    {{ article.titre }}
  {% endif %}
  {# On vérifie qu'une image est bien associée à l'article #}
  {% if article.image is not null %}
    <img src="{{ asset(article.image.webPath) }}" alt="{{ article.image.alt }}" class="img-thumbnail"/>
  {% endif %}
</h2>

<i>Le {{ article.date|date('d/m/Y') }}, par {{ article.auteur }}.</i>

{# On affiche les catégories éventuelles #}
{% if article.categories.count > 0 %}
  <div>
    <p class="text-danger bg-warning"><i>
      Catégories :
      {% for categorie in article.categories %}
        {{ categorie.nom }}{% if not loop.last %}, {% endif %}
      {% endfor %}
    </i></p>
  </div>
{% endif %}

<div class="well">
  {{ article.contenu }}
</div>

src/chris/NewsBundle/Resources/views/News/formulaire.html.twig
<div class="well">
  <form method="post" {{ form_enctype(form) }}>
	{# Les erreurs générales du formulaire. #}
	{{ form_errors(form) }}
	
	<div class="form-group">
	  {# Génération du label. #}
	  {{ form_label(form.titre, "Titre de l'article") }}
	
	  {# Affichage des erreurs pour ce champ précis. #}
	  {{ form_errors(form.titre) }}
	
	  {# Génération de l'input. #}
	  {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
	</div>
	
	{# Idem pour un autre champ. #}
	<div class="form-group">
	  {{ form_label(form.contenu, "Contenu de l'article") }}
	  {{ form_errors(form.contenu) }}
	  {{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}
	</div>
	
	  <div class="form-group">
           {{ form_label(form.image) }}
           {{ form_errors(form.image) }}
           {{ form_widget(form.image.file) }}
       </div>
      <div class="form-group">
	  {{ form_label(form.categories, "Catégories") }}
	  {{ form_errors(form.categories) }}
	  {{ form_widget(form.categories, {'attr': {'class': 'form-control'}}) }}
	</div> 
       
	{{ form_rest(form) }}
    <input type="submit" class="btn btn-primary" />
  </form>
</div>

src/chris/NewsBundle/Resources/views/News/menu.html.twig
<ul>
<h5><span class="glyphicon glyphicon-fire"></span>Dernières NEWS</h5>
<ul class="nav nav-pills nav-stacked">
  {% for article in liste_articles %}
    <li><a href="{{ path('chrisNewsVoir', {'slug': article.slug}) }}"> <span class="glyphicon glyphicon-chevron-right"></span>{{ article.titre }}</a></li>
  {% endfor %}
</ul>
</ul>

src/chris/NewsBundle/Resources/views/News/modifier.html.twig
{% extends "chrisNewsBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }} - Modifier un article
{% endblock %}

{% block newsBody %}

  <h2>Modifier une news</h2>

  {% include "chrisNewsBundle:News:formulaire.html.twig" %}

  <p>
    Vous éditez un article déjà existant,
    ne le changez pas trop pour éviter
    aux membres de ne pas comprendre
    ce qu'il se passe.
  </p>

  <p>
    <a href="{{ path('chrisNewsVoir', {'slug': article.slug}) }}" class="btn btn-default btn-success">
      Retour à l'article
    </a>
  </p>

{% endblock %}

src/chris/NewsBundle/Resources/views/News/supprimer.html.twig

{% extends "chrisNewsBundle::layout.html.twig" %}

{% block title %}
  Supprimer un article - {{ parent() }}
{% endblock %}

{% block newsBody %}

  <h2>Supprimer un article</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'article "{{ article.titre }}" ?
  </p>

  {# On met l'id de l'article dans la route de l'action du formulaire #}
  <form action="{{ path('chrisNewsSupprimer', {'id': article.id}) }}" method="post">
    <a href="{{ path('chrisNewsVoir', {'slug': article.slug}) }}" class="btn btn-default btn-warning">
      Retour à la News
    </a>
    <input type="submit" value="Supprimer" class="btn btn-default btn-danger" />
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/chris/NewsBundle/Resources/views/News/voir.html.twig
{% extends "chrisNewsBundle::layout.html.twig" %}

{% block title %}
   {{ parent() }} - Lecture d'une news
{% endblock %}

{% block newsBody %}
<div class="row">
	<div class="col-sm-3">
	   {% if prevSlug %}
	   <a href="{{ path('chrisNewsVoir', {'slug': prevSlug}) }}" class="btn btn-default btn-success">
	   <span class="glyphicon glyphicon-chevron-left"></span>News précédente : {{ prevSlug }}
	   </a>
	   {% else  %}
	  Aucune news précédente
	  {% endif %}
	  
	  </div>
	  <div class="col-sm-3 col-md-offset-6">
	  {% if nextSlug %}
	  <a href="{{ path('chrisNewsVoir', {'slug': nextSlug}) }}" class="btn btn-default btn-success">
	  News suivante : {{ nextSlug }}
	  <span class="glyphicon glyphicon-chevron-right"></span>
	  </a>
	   {% else  %}
	  Aucune news suivante
  	 {% endif %}
  	 </div>
  	 </div>
  {% include "chrisNewsBundle:News:article.html.twig" %}

  <p>
    <a href="{{ path('chrisNewsAccueil') }}" class="btn btn-default btn-success">
      Retour à la liste des News
    </a>
    {% if is_granted('ROLE_AUTEUR') %}
    <a href="{{ path('chrisNewsModifier', {'id': article.id}) }}" class="btn btn-default btn-warning">
      Modifier l'article
    </a>
    <a href="{{ path('chrisNewsSupprimer', {'id': article.id}) }}" class="btn btn-default btn-danger">
      Supprimer l'article
    </a>
    {% endif %}
  </p>

{% endblock %}